name: Deploy to GKE

on:
  push:
    branches:
      - main  # Change this if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker to Use Google Artifact Registry
      run: gcloud auth configure-docker gcr.io

    - name: Build & Push Backend Docker Image
      run: |
        docker build -t gcr.io/development-and-testing-451513/backend:latest backend/
        docker push gcr.io/development-and-testing-451513/backend:latest

    - name: Build & Push Frontend Docker Image
      run: |
        docker build -t gcr.io/development-and-testing-451513/frontend:latest frontend/
        docker push gcr.io/development-and-testing-451513/frontend:latest

    - name: Update Kubernetes Deployment
      run: |
        gcloud container clusters get-credentials cluster-1 --zone us-central1-a --project development-and-testing-451513
        kubectl set image deployment/backend backend=gcr.io/development-and-testing-451513/backend:latest
        kubectl set image deployment/frontend frontend=gcr.io/development-and-testing-451513/frontend:latest
name: Deploy to GKE

on:
  push:
    branches:
      - main  # Change this if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker to Use Google Artifact Registry
      run: gcloud auth configure-docker gcr.io

    - name: Build & Push Backend Docker Image
      run: |
        docker build -t gcr.io/development-and-testing-451513/backend:latest backend/
        docker push gcr.io/development-and-testing-451513/backend:latest

    - name: Build & Push Frontend Docker Image
      run: |
        docker build -t gcr.io/development-and-testing-451513/frontend:latest frontend/
        docker push gcr.io/development-and-testing-451513/frontend:latest

    - name: Update Kubernetes Deployment
      run: |
        gcloud container clusters get-credentials cluster-1 --zone us-central1-a --project development-and-testing-451513
        kubectl set image deployment/backend backend=gcr.io/development-and-testing-451513/backend:latest
        kubectl set image deployment/frontend frontend=gcr.io/development-and-testing-451513/frontend:latest
